/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestPanel.java
 *
 * Created on 28 oct. 2011, 18:00:19
 */
package test;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Paint;
import plegatfem.Node;

/**
 *
 * @author jmb2
 */
public class TestPanel extends javax.swing.JPanel {

    /** Creates new form TestPanel */
    public TestPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void paintComponent(Graphics g) {
        
        
        
        int h = this.getHeight();
        int w = this.getWidth();



        g.setColor(Color.WHITE);
        g.fillRect(0, 0, w, h);
        
        int nbPoints=3;
        int[] xPoints=new int[nbPoints];
        int[] yPoints=new int[nbPoints];
        
        xPoints[0]=w/10;
        xPoints[1]=w/10*9;
        xPoints[2]=w/10*2;
        
        yPoints[0]=h/10*9;
        yPoints[1]=h/10*7;
        yPoints[2]=h/10*1;
        
        Node[] nodes=new Node[3];
        nodes[0]=new Node("",xPoints[0], yPoints[0]);
        nodes[1]=new Node("",xPoints[1], yPoints[1]);
        nodes[2]=new Node("",xPoints[2], yPoints[2]);
        
        
        Graphics2D g2=(Graphics2D)g;
        
        
        MyPaint mp=new MyPaint(new ColorBandConvertor(0., 100.,20)); 
        mp.setNodes(nodes[0],nodes[1],nodes[2]);
        mp.setDisp(0., 0., 100., 0., 50., 0.);
        
        /*
        DispTria dt2=new DispTria(nodes[0],nodes[1],nodes[2]);
        dt2.setDispAtNodes(0., 0., 100., 0., 50., 0.);
        
        double[] disp2=dt2.getDisp(nodes[0].getX(),nodes[0].getY());
        System.out.println("node 0, attendu 0/0: "+disp2[0]+"/"+disp2[1]);
        
        /*
        disp2=dt2.getDisp(nodes[1].getX(),nodes[1].getY());
        System.out.println("node 1, attendu 50/0: "+disp2[0]+"/"+disp2[1]);
        disp2=dt2.getDisp(nodes[2].getX(),nodes[2].getY());
        System.out.println("node 2, attendu 100/0: "+disp2[0]+"/"+disp2[1]);
        */
        
        Paint pt=g2.getPaint();
        
        //g2.setPaint(new MyPaint(Color.orange, Color.red, 10, 5));
        g2.setPaint(mp);
        
        
        
        //g2.setColor(cbc.getIndexedColor(this.couleur));
        
        //g.drawPolygon(xPoints, yPoints, nbPoints);
        g.fillPolygon(xPoints, yPoints, nbPoints);

        g2.setPaint(pt);
        g.setColor(Color.black);
        g2.setStroke(new BasicStroke(2.0f,BasicStroke.CAP_BUTT,BasicStroke.JOIN_BEVEL));
        g.drawPolygon(xPoints, yPoints, nbPoints);
        
        
        // dessin second triangle
        
        xPoints[0]=w/10*7;
        xPoints[1]=w/10*9;
        xPoints[2]=w/10*2;
        
        yPoints[0]=h/10*3;
        yPoints[1]=h/10*7;
        yPoints[2]=h/10*1;
        
        nodes=new Node[3];
        nodes[0]=new Node("",xPoints[0], yPoints[0]);
        nodes[1]=new Node("",xPoints[1], yPoints[1]);
        nodes[2]=new Node("",xPoints[2], yPoints[2]);
       
        mp.setNodes(nodes[0],nodes[1],nodes[2]);
        mp.setDisp(0., 0., 100., 0., 50., 0.);
        
        g2.setPaint(mp);
        g.fillPolygon(xPoints, yPoints, nbPoints);

        
        
        
        g2.setPaint(pt);
        g.setColor(Color.black);
        g2.setStroke(new BasicStroke(2.0f,BasicStroke.CAP_BUTT,BasicStroke.JOIN_BEVEL));
        g.drawPolygon(xPoints, yPoints, nbPoints);
        
        
        
    }

    public int couleur=0;
    
}
