/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlegatFemGui.java
 *
 * Created on 16 oct. 2011, 20:46:17
 */
package gui;

import java.io.File;
import javax.swing.JFileChooser;
import plegatfem.Problem;
import testFem.ProblemImporter;

/**
 *
 * @author jmb2
 */
public class PlegatFemGui extends javax.swing.JFrame {

    private ProblemImporter pi;

    /** Creates new form PlegatFemGui */
    public PlegatFemGui() {
        initComponents();

    }

    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        plegatFemGuiPanel1 = new gui.PlegatFemGuiPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToggleButtonDisp = new javax.swing.JToggleButton();
        jToggleButtonMesh = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldEchelleDisp = new javax.swing.JTextField();
        jButtonSolve = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout plegatFemGuiPanel1Layout = new javax.swing.GroupLayout(plegatFemGuiPanel1);
        plegatFemGuiPanel1.setLayout(plegatFemGuiPanel1Layout);
        plegatFemGuiPanel1Layout.setHorizontalGroup(
            plegatFemGuiPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );
        plegatFemGuiPanel1Layout.setVerticalGroup(
            plegatFemGuiPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        jButton1.setText("Load");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jToggleButtonDisp.setText("Disp");
        jToggleButtonDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonDispActionPerformed(evt);
            }
        });

        jToggleButtonMesh.setText("Mesh");
        jToggleButtonMesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonMeshActionPerformed(evt);
            }
        });

        jLabel1.setText("Echelle disp:");

        jTextFieldEchelleDisp.setText("10");
        jTextFieldEchelleDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEchelleDispActionPerformed(evt);
            }
        });

        jButtonSolve.setText("Solve");
        jButtonSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolveActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("X");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Y");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("RES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSolve)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonMesh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonDisp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEchelleDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jButton2))
            .addComponent(plegatFemGuiPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButtonSolve)
                    .addComponent(jToggleButtonMesh)
                    .addComponent(jToggleButtonDisp)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldEchelleDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plegatFemGuiPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        final JFileChooser fc = new JFileChooser();

        int returnVal = fc.showOpenDialog(this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            
            this.pi=new ProblemImporter(file.getAbsolutePath());
            this.pi.importFile();
            
            this.jToggleButtonMesh.setSelected(false);
            this.jToggleButtonDisp.setSelected(false);
            
            this.plegatFemGuiPanel1.setProblem(this.pi.getPb());
        } 


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButtonMeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonMeshActionPerformed

        this.plegatFemGuiPanel1.setFlagDrawMesh(this.jToggleButtonMesh.isSelected());
        
    }//GEN-LAST:event_jToggleButtonMeshActionPerformed

    private void jTextFieldEchelleDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEchelleDispActionPerformed

        double value=Double.valueOf(this.jTextFieldEchelleDisp.getText());
        
        this.plegatFemGuiPanel1.setEchelleDisp(value);
        System.out.println("modif echelle");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEchelleDispActionPerformed

    private void jToggleButtonDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonDispActionPerformed

        this.plegatFemGuiPanel1.setFlagDrawDisp(this.jToggleButtonDisp.isSelected());
        
    }//GEN-LAST:event_jToggleButtonDispActionPerformed

    private void jButtonSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolveActionPerformed

        //this.pi.solve();
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSolveActionPerformed

    public void setProblem(Problem pb) {
        
        this.plegatFemGuiPanel1.setProblem(pb);
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlegatFemGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlegatFemGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlegatFemGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlegatFemGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PlegatFemGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonSolve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextFieldEchelleDisp;
    private javax.swing.JToggleButton jToggleButtonDisp;
    private javax.swing.JToggleButton jToggleButtonMesh;
    private gui.PlegatFemGuiPanel plegatFemGuiPanel1;
    // End of variables declaration//GEN-END:variables
}
