/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlegatFemGeoGui.java
 *
 * Created on 17 oct. 2011, 22:31:34
 */
package geom;

import java.util.ArrayList;
import plegatfem.Material;
import plegatfem.Node;
import plegatfem.Problem;
import plegatfem.Tri;

/**
 *
 * @author jmb2
 */
public class PlegatFemGeoGui extends javax.swing.JFrame {

    /** Creates new form PlegatFemGeoGui */
    public PlegatFemGeoGui() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        plegatFemGuiPanel1 = new gui.PlegatFemGuiPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("init");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plegatFemGuiPanel1Layout = new javax.swing.GroupLayout(plegatFemGuiPanel1);
        plegatFemGuiPanel1.setLayout(plegatFemGuiPanel1Layout);
        plegatFemGuiPanel1Layout.setHorizontalGroup(
            plegatFemGuiPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );
        plegatFemGuiPanel1Layout.setVerticalGroup(
            plegatFemGuiPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plegatFemGuiPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plegatFemGuiPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed



        GeoPoint p1 = new GeoPoint("1", 400, 0);
        GeoPoint p2 = new GeoPoint("2", 100, 0);
        GeoPoint p3 = new GeoPoint("3", 0, 100);
        GeoPoint p4 = new GeoPoint("4", 100, 200);
        GeoPoint p5 = new GeoPoint("5", 400, 200);

        Material mat = new Material("alu", 70000, 0.33);

        
        GeoQuad quad = new GeoQuad("1", p1, p2, p3, p4, 1, mat);
        quad.setNbElements(20, 5);
        quad.mesh(1, 1);

        /*
        GeoTri tri = new GeoTri("2", p2, p3, p5, 1, mat);
        tri.setNbElements(10);
        tri.mesh(50, 1, 1);
         * 
         */

        /*
        GeoQuadCircle qc=new GeoQuadCircle("1", p1, p2, p3, p4, p5, 1, mat);
        qc.setNbElements(15, 10, 10);
        qc.mesh(1,1);
        */
        
        Problem pb = new Problem();
        ArrayList<Node> listNode = quad.getNodes();
        ArrayList<Tri> listTri = quad.getTris();

        //ArrayList<Node> listNode2 = tri.getNodes();
        //ArrayList<Tri> listTri2 = tri.getTris();

        pb.addNode(listNode);
        //pb.addNode(listNode2);

        pb.addTri(listTri);
        //pb.addTri(listTri2);


        this.plegatFemGuiPanel1.setProblem(pb);
        this.plegatFemGuiPanel1.setFlagDrawMesh(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlegatFemGeoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlegatFemGeoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlegatFemGeoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlegatFemGeoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PlegatFemGeoGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private gui.PlegatFemGuiPanel plegatFemGuiPanel1;
    // End of variables declaration//GEN-END:variables
}
